#!/usr/bin/env bash
# a Bash script that configures an
# Ubuntu server with the below requirements

sudo cp /etc/hosts ~/hosts.new
sed -i 's/^127.*/127.0.0.2 localhost/' ~/hosts.new
sed -i '1 a 8.8.8.8 facebook.com' ~/hosts.new
cp -f ~/hosts.new /etc/hosts

